### ISSUE TITLE
BuildInfo causing toolbar labels to disappear

### ISSUE THREAD

**Issue by mvs5465** [THDigi/BuildInfo#3]
Hey, seems like this mod might be affecting the labels on a toolbar.

When the mod is installed, toolbar labels are missing:
![with_build_info](https://user-images.githubusercontent.com/12912578/153309870-b410f858-9678-480d-8328-da09c1ef2ca1.png)

After the mod is uninstalled, toolbar labels return:
![without_build_info](https://user-images.githubusercontent.com/12912578/153309913-e0944d71-17dd-4d62-ba28-9329f71815dd.png)

**Comment by THDigi** [comment]
It's because of a HUD mod increasing font size there, I already have a fix in the bleeding edge version that will come to the normal one sometime soon :}

**Comment by mvs5465** [comment]
Sweet, thanks @THDigi !
